paths:
  raw_xmp_dir: data/raw/xmp
  raw_lrtemplate_dir: data/raw/lrtemplate
  processed_dir: data/processed

extract:
  include_xmp: true
  include_lrtemplate: true
  output_basename: presets
  output_formats: [csv, jsonl]
  csv:
    delimiter: ","
    quotechar: '"'
  jsonl:
    indent: 0

